### ISSUE TITLE
Create basic extension structure. 

### ISSUE THREAD

**Issue by dzonekl** [AxonFramework/extension-tracing#1]
- add travis
- add docs. 
- do a test build

**Comment by smcvb** [comment]
Having a `.travis.yml` should suffice for the pull request to be taken into account by Travis for verification.
Along side that, things like a `.gitattributes`, `.gitignore`, `LICENSE.txt`, `README.md` and a `pom.xml` would suffice.

I might need to assign it in Travis once the first PR is there. 
Regardless, the travis file should be sufficient to show it builds :-)

**Comment by dzonekl** [comment]
Ok, well I am pushing on master right now :-)
So this story is kind of done, can I access travis to see the build ?

**Comment by smcvb** [comment]
Ah, wasn't aware you had that - good to know!

Notice Travis (and Codacy + CLAHub) weren't set yet for `extension-tracing`, so I just did that..
Now you should automatically have Travis, Codacy and CLAHub checks on every PR.
From there on, you can click on the Travis icon to see the status.

Rights to adjust it are however tied to more global rights to the overall Axon Framework organization - let's first see if these settings are sufficient before proceeding further.

**Comment by smcvb** [comment]
A part from that, I've seen you've resolved this first issue.
Hence, I'll be closing this issue as resolved - thanks for the work @dzonekl!
