### ISSUE TITLE
Why doesn't TracingCommandGateway#sendAndWait activate the span?

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#11]
in `TracingCommandGateway#send` we do see the span activation and in `TracingCommandGateway#sendAndWait` we don't. Why is that?

**Comment by dzonekl** [comment]
I think we only restore the active span, at the completable future, so a sync call would not restore the span. In other words, it's simply not implemented.

**Comment by smcvb** [comment]
I am sorry @Sam-Kruglov and @dzonekl, but I don't see this discrepancy between the `send` and `sendAndWait` methods.

The only spot where `Tracer#activateSpan()` is called in the `TracingCommandGateway` is in the `sendWithSpan(Tracer, String, CommandMessage<?>, SpanConsumer)` method.

I do acknowledge that the `send` method will call this method right after it has wrapped the `commandPayload` in a `CommandMessage`, on line 82.
The `sendAndWait` method calls `doSendAndExtract` which starts on line 182, which in turn on line 112 calls the `sendAndRestoreParentSpan(Object, FutureCallback<Object, R>)` .

The latter will, just as the `send()` method, call the `sendWithSpan(Tracer, String, CommandMessage<?>, SpanConsumer)` function, which will call `Tracer#activateSpan()`.

So, is my train of thought in correct on this? Is my conception on the inner workings of the `Tracer` incorrect?
I'd much value your guys input on this, Sam and Christophe!

**Comment by Sam-Kruglov** [comment]
@smcvb Sorry, I don't really know what I meant now. I think I may have been confused with the callback in `#send`. But you're right

**Comment by smcvb** [comment]
No problem @Sam-Kruglov! I think we've alleviated the concern through our discussion. Thanks for closing the issue and thanks again for your interest in the framework! :-)
