### ISSUE TITLE
Existing parent span not deactivated when invoking CommandGateway

### ISSUE THREAD

**Issue by jvanderkallen** [AxonFramework/extension-tracing#16]
**Current Behavior**
If I place a command on the TracingCommandGateway with send or sendAndWait and there already is an active span before the TracingCommandGateway is invoked then it will not be deactivated. I close the span after invoking the TracingCommandGateway. If I don't invoke the TracingCommandGateway then the span is closed.

**Expected Behavior**
I expect the span that was created before invoking the TracingCommandGateway to be deactivated at the end of the try with statement. I have [attached a project](https://github.com/AxonFramework/extension-tracing/files/3317073/axon-tracing-parent-not-deactivated.tar.gz) to demonstrate the behavior. Am I doing something wrong or is this extension exhibiting undesirable behavior? If I don't invoke the CommandGateway within the try with statement then the span is deactivated.

**Comment by dzonekl** [comment]
Hi, I haven't looked at the code you submitted (yet), but I do expect an active span, as the dependency on opentracing, will already have hooked in an HTTP filter, to create an active span. (Assuming you fire a command, from having invoked an HTTP request). This span becomes the parent span indeed, and is not deactivated. 

The idea, is/was that you won't need to do anything special like wrapping try/catch or anything else when invoking the Tracing*Gateways. It's cross cutting, and opentracing will add instrumentation to many libraries which are your classpath. 

We didn't create the parentspan, so why should we finish it?

**Comment by jvanderkallen** [comment]
Thanks for your reply. I suggest you look at my example code. I don't expect this project to deactivate the parent span. For some reason the span that I create in my code is not deactivated when I deactivate it and invoke the TracingCommandGateway. If I do not invoke the TracingCommandGateway and deactivate it then it is deactivated.

**Comment by dzonekl** [comment]
I will try to find some time to have a look at the project you submitted. Not sure why we would do anything with a span, while the Tracing code is not invoked...

**Comment by jvanderkallen** [comment]
I have submitted a pull request which fixes the problem, I believe. I would appreciate it if you could review it.

**Comment by Sam-Kruglov** [comment]
Can we deploy this change? This makes current command gateway unusable as all tracing gets smashed under the first recorded command

**Comment by smcvb** [comment]
Yes we can @Sam-Kruglov, please be patient. We have more to do than just the Tracing Extension ;-)
Aiming to release 4.3 of this extension this week, so no worries.
