### ISSUE TITLE
Add Springboot auto-config for tracing components

### ISSUE THREAD

**Issue by dzonekl** [AxonFramework/extension-tracing#2]
Configure Tracing GW's. 
Configure Dispatch Interceptor
Configure Handler Interceptor.

**Comment by dzonekl** [comment]
@smcvb  How do you test extensions in an application? Do you use giftcard app?

**Comment by smcvb** [comment]
@dzonekl I typically leverage the GiftCard app for stuff like that, correct :-)

**Comment by dzonekl** [comment]
@smcvb I am bit confused about the giftcard app, the readme says it can be started distributed with profiles, but I don't see profile definitions in mvn, no child pom.xml for the individual services. Is it distributed? (Which is kind of relevant for showing the tracing in action).

**Comment by dzonekl** [comment]
@smcvb oh nevermind, these are spring profiles, not maven...

**Comment by dzonekl** [comment]
Merged.
