### ISSUE TITLE
Add aggegrate identifier as trace tag

### ISSUE THREAD

**Issue by gerloh** [AxonFramework/extension-tracing#22]
Would it be nice/usefull to add the aggregateIdentifier als a tracing tag ? 
(Only in case of a DomainEventMessage) 
That way it is more easy to find a specific trace without having to lookup the traceId first, or by just looking at the start time .

**Comment by gerloh** [comment]
made a PR for this : 
https://github.com/AxonFramework/extension-tracing/pull/23
@abuijze  what do you think ?

**Comment by gerloh** [comment]
Or maybe it should be configurable, by assigning metadata properties to be used as tags ..

**Comment by smcvb** [comment]
I think it's very reasonable to add this to the span @gerloh.

Making it configurable would be even more awesome!
I do feel though that's another feature entirely, providing more configurability about the tags you'd want to trace. 

As such, for now I feel this idea is sufficient on it's own accord.

**Comment by gerloh** [comment]
Ah thanks! I wil look in some configuration possibilities. Also i have some ideas about the operator names. Will make a PR for that too.
