### ISSUE TITLE
Operation names proposal

### ISSUE THREAD

**Issue by gerloh** [AxonFramework/extension-tracing#26]
I would like to suggest other operation names for the spans. Now it is
"sendCommand" , "sendAndWaitCommand" and "handleEventMessage" ,"handleCommand" ,
but it also "handle\<QueryName>".
This not consistent and not really clear when looking at the traces in Jeager.
I would like to propose : 
"send\<CommandName>"
"sendAndWait\<CommandName>"
"send\<QueryName>" 
"handle\<CommandName>
"handle\<QueryName>"
"handle\<EventPayloadtype>
Also use simpleNames if the Command and Query classNames are not overruled by commandName and queryName

From the messagenames it mostly is clear that it is an event, command or query.

See https://github.com/AxonFramework/extension-tracing/pull/25

So it looks like this :
 
![image](https://user-images.githubusercontent.com/12526626/75610206-5eb86000-5b0f-11ea-823d-bf0e3c049ff3.png)

**Comment by smcvb** [comment]
Closing this issue as it has been resolved through pull request #25.
