### ISSUE TITLE
Opentracing removed deprecated methods

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#34]
If I declare this:
```xml
<dependency>
    <groupId>org.axonframework.extensions.tracing</groupId>
    <artifactId>axon-tracing-spring-boot-starter</artifactId>
    <version>4.2-M1</version>
</dependency>
<dependency>
    <groupId>io.opentracing.contrib</groupId>
    <artifactId>opentracing-spring-jaeger-web-starter</artifactId>
    <version>3.1.1</version>
</dependency>
```

You are using deprecated methods inside `opentracing-api:0.32.0`, I bring in `0.33.0` which removed those methods, so, when I browse axon sources, I see "red method calls". For example, see `io.opentracing.Tracer.SpanBuilder`.

Also, if you visit [opentracing.io](https://opentracing.io/), you will see they seem to be called `OpenTelemetry` now.

**Comment by smcvb** [comment]
I am unsure which specific dependencies you feel require updating right now. 
Another contributor did an effort to upgrade to 0.33.0 in pull request #21 (marked under issue #20 by the way).

I would thus assume what you are stating has already been resolved.
Can you be bit more specific what should be updated to a more recent version?

Mind you, the upgrade is part of the `master` branch, hence it would require a snapshot build from your part at the moment. I am guessing this is the predicament, as you are using `4.2-M1`.

**Comment by Sam-Kruglov** [comment]
yes, seems it's done already, just after `4.2-M1`
