### ISSUE TITLE
Make FailureLoggingCallback into an optional interceptor.

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#37]
In #15, I had to override a `DefaultCommandGateway` in order to copy-paste the `send` method to exclude the `FailureLoggingCallback` so that it doesn't pollute my logs. I have my own very cool logging interceptors that log all messages (see `io.axoniq.demo.bikerental.config.tracing.TracingAxonConfig.Logging`):
- Command payloads at DEBUG
- User-friendly events at INFO
- Event payloads at DEBUG
- Query payloads at TRACE
- Query return values at TRACE

I suggest that you turn that callback into an interceptor that I can disable/replace or/and you can take my idea for logging. 

P.S. whenever we log anything in the tracing context, we must also log trace id or it's going to be a mess.

**Comment by smcvb** [comment]
Gotcha on the argument, another `CommandCallback` implementation might be nice to introduce.

However, you should regard the `FailureLoggingCallback` as optional already.
Check out the `public <C, R> void send(C command, CommandCallback<? super C, ? super R> callback) { ... }` method which is present. That is exactly what you are looking for, as it provide the option to define your own `CommandCallback` implementation which does the logging you've created.

I thus feel this issue has already been covered and as such I will close it.

**Comment by Sam-Kruglov** [comment]
Hmm alright then, thanks

**Comment by Sam-Kruglov** [comment]
It doesn't seem I can do any better than this copy-pasting. Can we maybe have this exceptional result transformation into a util static method?
https://github.com/Sam-Kruglov/bike-rental-demo/blob/ebfcf58c9809fa1157b08be6555aadd67bfcc67e/src/main/kotlin/io/axoniq/demo/bikerental/config/CustomDefaultCommandGateway.kt
I think this part is duplicated in the command gateway also and maybe somewhere else

**Comment by smcvb** [comment]
What you want to unwrap a `CommandResultMessage` to is very much implementation specific. The `CommandGateway` provides a simplified convenience API compared to the `CommandBus` directly, which has decided to use the `CompletableFuture`. What if you want to, let's say return a `Mono` [instead](https://github.com/AxonFramework/AxonFramework/pull/1337)? That would completely alter the requirements for such a static utility method.

It is indeed duplicated at the moment, but only from the the `DefaultCommandGateway` to the `TracingCommandGateway`. Even though it'll enhance the code slightly (and simplify your life), I feel it's a little overboard given our intent to eventually drop the use of the tracing gateway in favor of a pure interceptor solution (as already mentioned on [your PR](https://github.com/AxonFramework/extension-tracing/pull/39)).

So, I gotcha Sam, but for now I think this is still rather trivial to implement for the end user.
As always, you and others are still free to keep commenting on this issue for further reasoning.
