### ISSUE TITLE
Demo application, demonstrating tracing

### ISSUE THREAD

**Issue by dzonekl** [AxonFramework/extension-tracing#4]
This is an issue to track progress, of demo'ing this extension with the giftcard app.

**Comment by dzonekl** [comment]
![image](https://user-images.githubusercontent.com/295240/52061192-14f8f100-256e-11e9-9c3a-4b2607dcc773.png)

**Comment by dzonekl** [comment]
When running giftcard distributed, it looks like this: 

![image](https://user-images.githubusercontent.com/295240/52062228-65714e00-2570-11e9-9089-bc8f804d8a21.png)

**Comment by dzonekl** [comment]
And for the command, we get an exception: 

![image](https://user-images.githubusercontent.com/295240/52062849-91410380-2571-11e9-87ad-dc1a0467107b.png)

**Comment by dzonekl** [comment]
Aha... we don't support sendAndWait ... we create issue for this.

**Comment by dzonekl** [comment]
Added tracing to sync. methods and a correlationdata provider, so now we can follow the message all the way to the event handler. 


![image](https://user-images.githubusercontent.com/295240/52284923-b369c580-2965-11e9-88c8-580835b5de38.png)

**Comment by dzonekl** [comment]
@abuijze @smcvb I think by now we have a working tracing extension (Except subscription queries)
 I have a branch on forked giftcard repo., which enables tracing and has a docker-compose with Jaeger to visualize it. I would like to blog about this...Would you like a PR on giftcard for this ?

**Comment by smcvb** [comment]
I think it's fine to not have this directly under the GiftCard demo application. I'd rather refer to our community, aka your blog, when talking about this stuff. I think you deserve the credits. :-)

As the blog has been published already, I think it's fine to close this issue for the time being.
