### ISSUE TITLE
Subscription query in TracingQueryGateway won't work?

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#41]
I didn't test it but your test doesn't look promising as it's using simply `new DefaultSubscriptionQueryResult<>(Mono.empty(), Flux.empty(), () -> true)` as a stub result.

If we unwrap the code this is essentially what it's doing:
```java
Span childSpan = tracer.buildSpan(operation).start();
try (Scope ignored = tracer.activateSpan(childSpan)) {
    return new TraceableSubscriptionQueryResult<>(
                                   delegate.subscriptionQuery(
                                           queryName,
                                           query,
                                           initialResponseType,
                                           updateResponseType,
                                           backpressure,
                                           updateBufferSize),
                                   childSpan
                           ));
}
...
class TraceableSubscriptionQueryResult{
...
  @Override
  public Mono<I> initialResult() {
      span.log("initialResultReceived");
      return initialResult;
  }
  @Override
  public Flux<U> updates() {
      return updates.doOnEach(ignored -> span.log("updateReceived"));
  }
}
```

I think that when you call `delegate.subscriptionQuery(...)` it's going to return an async result and then populate it later. If that's true, the `childSpan` scope will close as soon as that happens. Later, on `initialResult` and on `update` we will call `childSpan.log(...)` which will fail for sure as it is out of scope.

One can use `StepFerifier` somehow or the `Awaitility` library introduced in #39 to test this with a delay.

---
P.S. Can we replace `SpanSupplier<T>` with `java.util.function.Supplier<Span>`?

**Comment by lfgcampos** [comment]
Hi @Sam-Kruglov, I've create the PR #42 while playing with this issue.
An additional test case was made to make sure it is working as expected.

Other than that, I've also played with tracing on a personal project that is using `subscriptionQuery` and it worked as expected (using `jaeger` in my case).

Feel free to check the PR and comment here/there if you think it is needed.

**Comment by Sam-Kruglov** [comment]
> call childSpan.log(...) which will fail for sure as it is out of scope.
Well, turns out that's not true, you can call `Span#log` outside of scope just fine, so there's no issue
