### ISSUE TITLE
Query payload type tag is wrong

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#44]
This line assigns message type in place of payload type:
https://github.com/AxonFramework/extension-tracing/blob/80d3633bc280efd7c9c62822327508c4b7166dfa/tracing/src/main/java/org/axonframework/extensions/tracing/SpanUtils.java#L56

Method below used by command gateway is correct:
https://github.com/AxonFramework/extension-tracing/blob/80d3633bc280efd7c9c62822327508c4b7166dfa/tracing/src/main/java/org/axonframework/extensions/tracing/SpanUtils.java#L70

**Comment by smcvb** [comment]
Darnit, good one Sam. I'll get a fix in right away!

**Comment by smcvb** [comment]
Closing this issue as it has been resolved in commit 72c8b15.
