### ISSUE TITLE
Auto configuration is not flexible enough

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#47]
I just want to define `@Bean`s of `MessageDispatchInterceptor`, `MessageHandlerInterceptor`, and `ListenerInvocationErrorHandler` and I don't want to deal with anything else.

Take a look at how I'm defining those beans in [TracingAxonConfig](https://github.com/Sam-Kruglov/bike-rental-demo/blob/master/src/main/kotlin/io/axoniq/demo/bikerental/config/tracing/TracingAxonConfig.kt) and how I'm catching those in [AxonConfig](https://github.com/Sam-Kruglov/bike-rental-demo/blob/master/src/main/kotlin/io/axoniq/demo/bikerental/config/AxonConfig.kt).

Note, how I'm using `@Bean @Order(0)` on the tracing interceptor, `@Bean @Onder(1)` on exception handling ones, and `@Bean` (comes last) on others. That controls the ordering in the `List` that I'm catching later, and, mainly, the invocation order.

This concerns both `TracingAutoConfiguration` and `AxonAutoConfiguration` (from core).

**Comment by smcvb** [comment]
Issue moved to [AxonFramework/AxonFramework #1422](https://github.com/AxonFramework/AxonFramework/issues/1422) via [**ZenHub**](https://www.zenhub.com/)
