### ISSUE TITLE
Suggesting to put traceId into console logs

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#50]
In a production environment, looking at console logs without traceId is nearly impossible because multiple requests from multiple machines write their own things into the same file, and it's very hard to make sense of it.

It is all right if we're looking at the logs via Open Tracing UI that are attached to a span but if we are talking about console logs, it's a different story.

> Sensible to include and simple enough to achieve on a users own accord I think. Don't think this requires anything extension specific right now.
(c) @smcvb #15

I think library user is supposed to deal with it themselves in a usual case but this extension is aware of tracing, so, it should use it IMO.

Example:
```kotlin
log.info("[${tracer.activeSpan()?.context()?.toTraceId()}]: ${command.payloadType.simpleName} has been dispatched")
```
Will print:
```
[e66dc77b8a1e813b]: RegisterBikeCommand has been dispatched
```

**Comment by abuijze** [comment]
Hi Sam,

while this is a really nice feature, I don't think it belongs to Axon to provide it. In fact, many logging systems already allow you to add MDC data to the log lines, by defining them in the log pattern. Span IDs make good sense as MDC information.

I would be surprised if there isn't already some feature in OpenTracing to add the span ID to the MDC, or have your logging implementation read the trace ID from a thread local when writing it.
