### ISSUE TITLE
Suggesting opt-in configuration to include message payload into tags

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#51]
From #15.

I think it could be useful to have a possibility to set a property to start including message payloads as span tags. I agree it should default to **not** do that.

**Comment by smcvb** [comment]
Agreed. Being able to configure the naming would be a nice to have. I envision an approach where the "tab building components" are configurable through the `Builder` of each component as `Function` instances/functional interface. They'd than default to the work currently performed by the `SpanUtils` static methods, with the option to be overridden to whatever the user desire. For example, the message's payload name.
