### ISSUE TITLE
Property for disabling an extension

### ISSUE THREAD

**Issue by dmurat** [AxonFramework/extension-tracing#53]
Can you consider adding a property that will disable tracing?

It might be more convenient than poking around with dependencies if tracing, for some reason, isn't desired in different environments (dev, qa, prod, etc.).

Tnx.

**Comment by dmurat** [comment]
Found a way via `spring.autoconfigure.exclude`:

    spring.autoconfigure.exclude:
      - org.axonframework.extensions.tracing.autoconfig.TracingAutoConfiguration

**Comment by abuijze** [comment]
Reopening, because I agree with you. Deselecting it from the auto configuration is a workaround IMHO. You shouldn’t have to be aware of the class names in the extension.

**Comment by dmurat** [comment]
Great :-)

FYI, I tried this extension with Spring Boot 2.3.0 and its Wavefront integration with build-in tracing, and it works perfectly :-)

**Comment by smcvb** [comment]
Closing this issue as it has been resolved in pull request #55.
