### ISSUE TITLE
Define default trace operation name and tags from messages.

### ISSUE THREAD

**Issue by dzonekl** [AxonFramework/extension-tracing#7]
Message information like: 

- Message id
- Message type (Command, Query, Event etc..) 
- Payload type. 
- Payload size

Could be added as tags to the span or as the operation name of a span. 

Now child spans are created with the following names: 

Command Gateway -> child span named 'Command'
Query Gateway -> child span named 'Query'
HandlerInterceptor -> child span named 'Extracting'

DispatchInterceptor -> no child span.
CorrelationDataProvider -> no child span.

Propose: 

Operation name
- Message payload type 

Tags: 
- Axon message id. 
- Message type. 
- Message payload type
- Message payload size

@abuijze @smcvb  what do you think?

**Comment by smcvb** [comment]
This doesn't sound to off for me. 
If any, I think this should be configurable for users rather than set in stone - taking several sensible defaults of course.
@abuijze do you have any other opinions on this?

**Comment by dzonekl** [comment]
- in Querygateway use dispatch[Query/Command ]name
- in Handler interceptor, use handler[Query/Command] name

(See CommandMessage, getCommandName).
