### ISSUE TITLE
Do not use @Primary @Bean in auto configuration

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#8]
The user should be able to simply provide their own beans.
https://github.com/AxonFramework/extension-tracing/blob/b2975cde31a8fe027e73904f4e4455d9a507e646/tracing-spring-boot-autoconfigure/src/main/java/org/axonframework/extensions/tracing/autoconfig/TracingAutoConfiguration.java#L60

**Comment by smcvb** [comment]
`@Primary` would've been fine, granted that a `@ConditionalOn...` would've been needed in that scenario. Regardless, I do not see why these are annotated with `Primary`. 
I'll replace them for `@ConditionalOnMissingBean`.

Thanks for bringing this to light @Sam-Kruglov, helpful as always! :-)
